name: lotto_music
description: one proyect for avaluos.

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Core
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.9
  #Servicios http
  http: ^0.13.4
  dio: ^4.0.6
  #funcionalidades
  #image_picker: ^0.8.5
  flutter_svg: ^1.0.3
  socket_io_client: ^2.0.0
  #youtube 
  youtube_player_flutter: ^8.1.0
  #animation 
  animate_do: ^2.1.0
  #others
  easy_debounce: ^2.0.2+1
  flutter_credit_card: ^3.0.1
  flutter_image_compress: ^1.1.0
  syncfusion_flutter_charts: ^20.2.44
  localstorage: ^4.0.0+1
  permission_handler: ^10.0.0
  



#funciones para desarrolador
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  android: true
  #flutter pub run flutter_launcher_icons:main 

flutter_native_splash:
  image: "assets/logo/logo.png"
  color: "#FFFFFF"
  image_dark: "assets/logo/logo.png"
  color_dark: "#000000"
  android: true
  ios: true
  #flutter pub run flutter_native_splash:create


flutter:
  uses-material-design: true
  assets:
    - assets/appUtils/
    - assets/svg/imagenes/
    - assets/svg/logos/
    - assets/background/
    - assets/logo/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 500

    - family:  NewIcons
      fonts:
        - asset: assets/icons/fonts/NewIcons.ttf

flutter_intl:
  enabled: true
  main_locale: es
  class_name: AppLocalisations


#svg atributes 
# https://undraw.co/search
# https://www.svgbackgrounds.com/

#New Icons
# https://www.fluttericon.com/